on: [push, workflow_dispatch]

jobs:
  deploy_to_caprover:
    runs-on: ubuntu-latest
    name: Deploy to CapRover
    steps:
      - uses: actions/checkout@v3
      - uses: adamghill/build-docker-and-deploy-to-caprover@v1
        with:
          caprover-app-name: django-unicorn-web
          github-token: ${{ secrets.GITHUB_TOKEN }}
          caprover-server-url: ${{ secrets.CAPROVER_SERVER_URL }}
          caprover-app-token: ${{ secrets.CAPROVER_APP_TOKEN }}
